from app.modules.category_classificator.controllers.c_classifier import ClassifierController
from app.modules.category_classificator.controllers.c_predict import PredictController
from app.modules.category_classificator.controllers.c_train_model import TrainModelController
